# This file was generated by GoReleaser. DO NOT EDIT.
cask "claw-radio-cli" do
  name "claw-radio-cli"
  desc "GTA-style AI radio station CLI - operated by an AI agent"
  homepage "https://github.com/vossenwout/claw-radio"
  version "0.0.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "claw-radio"

  on_macos do
    url "https://github.com/vossenwout/claw-radio/releases/download/v#{version}/claw-radio_#{version}_darwin_all.tar.gz"
    sha256 "fcf9a7b2e6dba907e5aa6332cc83b7cf75d8f720b572a8f8da0e5c31a8d22198"
  end

  on_linux do
    on_intel do
      url "https://github.com/vossenwout/claw-radio/releases/download/v#{version}/claw-radio_#{version}_linux_amd64.tar.gz"
      sha256 "3fa7bdd84ac51c7d87bf00a281461a417053d03bf980216d17cda055cb83767f"
    end
    on_arm do
      url "https://github.com/vossenwout/claw-radio/releases/download/v#{version}/claw-radio_#{version}_linux_arm64.tar.gz"
      sha256 "8f755943f3ff9787b18b571b8f967c5ca29273edf2a56b31e8fb7ea5e2c23640"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/claw-radio"]
    end
  end

  caveats do
    "Install required tools:"
    "  brew install mpv yt-dlp ffmpeg docker colima"
    ""
    "Start the container runtime:"
    "  colima start"
    ""
    "Run SearxNG:"
    "  docker run -d --name searxng -p 127.0.0.1:8888:8080 searxng/searxng:latest"
    ""
    "Optional (high-quality TTS voice):"
    "  claw-radio tts install"
  end

  # No zap stanza required
end
