# This file was generated by GoReleaser. DO NOT EDIT.
cask "macos-audio-cli" do
  name "macos-audio-cli"
  desc "macOS Bluetooth and audio output management CLI"
  homepage "https://github.com/vossenwout/macos-audio"
  version "0.0.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "macos-audio"

  on_macos do
    url "https://github.com/vossenwout/macos-audio/releases/download/v#{version}/macos-audio_#{version}_darwin_all.tar.gz"
    sha256 "2b44217c251690e308638c2f9e4c242d7169f2850e58590362fc063d4e684676"
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/macos-audio"]
    end
  end

  caveats do
    "macos-audio requires blueutil and switchaudio-osx:"
    "  brew install blueutil switchaudio-osx"
    ""
    "Use `macos-audio scan` to list targets, then `macos-audio connect bt <name|mac>`, `macos-audio connect airplay`, or `macos-audio connect local <name>`."
  end

  # No zap stanza required
end
